/**
 * Google reCAPTCHA Enterprise Assessment Helper
 * Formats and posts assessment requests to the reCAPTCHA Enterprise REST API.
 */

export const RECAPTCHA_SITE_KEY = "6LdE1oAtAAAAADjSeIu16iRH5Hh4lD28HmKHqE6-";

export interface RecaptchaAssessmentPayload {
  event: {
    token: string;
    expectedAction: string;
    siteKey: string;
  };
}

export interface RecaptchaAssessmentResponse {
  name?: string;
  event?: {
    token: string;
    expectedAction: string;
    siteKey: string;
  };
  riskAnalysis?: {
    score: number;
    reasons?: string[];
  };
  tokenProperties?: {
    valid: boolean;
    invalidReason?: string;
    action?: string;
    createTime?: string;
  };
}

/**
 * Gets the current token generated by the reCAPTCHA Enterprise widget.
 */
export function getRecaptchaToken(): string | null {
  if (typeof window !== 'undefined' && (window as any).grecaptcha?.enterprise) {
    try {
      const response = (window as any).grecaptcha.enterprise.getResponse();
      if (response) return response;
    } catch (e) {
      console.warn('grecaptcha.enterprise.getResponse() warning:', e);
    }
  }

  // Fallback to reading the hidden input generated by reCAPTCHA
  if (typeof document !== 'undefined') {
    const textarea = document.querySelector<HTMLTextAreaElement>('textarea[name="g-recaptcha-response"]');
    if (textarea && textarea.value) {
      return textarea.value;
    }
  }

  return null;
}

/**
 * Evaluates a reCAPTCHA Enterprise token via the Google reCAPTCHA Enterprise REST API.
 *
 * Endpoint: POST https://recaptchaenterprise.googleapis.com/v1/projects/{projectId}/assessments?key={apiKey}
 * Request Body:
 * {
 *   "event": {
 *     "token": "TOKEN",
 *     "expectedAction": "USER_ACTION",
 *     "siteKey": "6LdE1oAtAAAAADjSeIu16iRH5Hh4lD28HmKHqE6-"
 *   }
 * }
 */
export async function createRecaptchaAssessment(
  token: string,
  expectedAction: string,
  projectId?: string,
  apiKey?: string
): Promise<RecaptchaAssessmentResponse> {
  const gcpProjectId = projectId || import.meta.env.VITE_FIREBASE_PROJECT_ID || "shawstemacademy-c0039";
  const gcpApiKey = apiKey || import.meta.env.VITE_FIREBASE_API_KEY || "";

  const url = `https://recaptchaenterprise.googleapis.com/v1/projects/${gcpProjectId}/assessments?key=${gcpApiKey}`;

  const payload: RecaptchaAssessmentPayload = {
    event: {
      token,
      expectedAction,
      siteKey: RECAPTCHA_SITE_KEY,
    },
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`reCAPTCHA Assessment API error (${response.status}): ${errorText}`);
  }

  return await response.json();
}
